package com.sullivan.gareth;

public interface HtmlContent {

    String TITLE = "Name And Age Submission Form";
    
    String EXAMPLE_FORM = "<html>" + "\r\n"
            +"    <head>" + "\r\n"
            +"        <title>"+TITLE+"</title>" + "\r\n"
            +"    </head>" + "\r\n"
            +"    <body>" + "\r\n"
            +"        <form action=\"/\" method=\"post\" id=\"signupForm\">" + "\r\n"
            +"            <table>" + "\r\n"
            +"                <tr>" + "\r\n"
            +"                    <td>Name:</td>" + "\r\n"
            +"                    <td><input type=\"text\" id=\"myName\" name=\"name\" value=\"\" /></td>" + "\r\n"
            +"                </tr>" + "\r\n"
            +"                <tr>" + "\r\n"
            +"                    <td>Age:</td>" + "\r\n"
            +"                    <td><input type=\"text\" id=\"myAge\" name=\"age\" value=\"\" /></td>" + "\r\n"
            +"                </tr>" + "\r\n"
            +"                <tr>" + "\r\n"
            +"                    <td><button type=\"submit\" id=\"mySubmitButton\">Submit</button></td>" + "\r\n"
            +"                </tr>" + "\r\n"
            +"            </table>" + "\r\n"
            +"        </form>" + "\r\n"
            +"        <table id=\"bookResults\">" + "\r\n"
            +"            <thead>" + "\r\n"
            +"                <tr>" + "\r\n"
            +"                    <th>Title</th>" + "\r\n"
            +"                    <th>Author</th>" + "\r\n"
            +"                    <th>Format</th>" + "\r\n"
            +"                    <th>Price</th>" + "\r\n"
            +"                    <th>Release Date</th>" + "\r\n"
            +"                </tr>" + "\r\n"
            +"            </thead>" + "\r\n"
            +"            <tbody>" + "\r\n"
            +"                <tr>" + "\r\n"
            +"                    <td>Zero History</td>" + "\r\n"
            +"                    <td>William Gibson</td>" + "\r\n"
            +"                    <td>Hardback</td>" + "\r\n"
            +"                    <td>£12.29</td>" + "\r\n"
            +"                    <td>2 Sep 2010</td>" + "\r\n"
            +"                </tr>" + "\r\n"
            +"                <tr>" + "\r\n"
            +"                    <td>Zero History</td>" + "\r\n"
            +"                    <td>William Gibson</td>" + "\r\n"
            +"                    <td>Kindle</td>" + "\r\n"
            +"                    <td>£11.99</td>" + "\r\n"
            +"                    <td>2 Sep 2010</td>" + "\r\n"
            +"                </tr>" + "\r\n"
            +"                <tr>" + "\r\n"
            +"                    <td>Spook Country</td>" + "\r\n"
            +"                    <td>William Gibson</td>" + "\r\n"
            +"                    <td>Paperback</td>" + "\r\n"
            +"                    <td>£5.00</td>" + "\r\n"
            +"                    <td>31 Jul 2008</td>" + "\r\n"
            +"                </tr>" + "\r\n"
            +"                <tr>" + "\r\n"
            +"                    <td>Pattern Recognition</td>" + "\r\n"
            +"                    <td>William Gibson</td>" + "\r\n"
            +"                    <td>Paperback</td>" + "\r\n"
            +"                    <td>£4.99</td>" + "\r\n"
            +"                    <td>24 Jun 2004</td>" + "\r\n"
            +"                </tr>" + "\r\n"
            +"            </tbody>" + "\r\n"
            +"    </body>" + "\r\n"
            +"</html>";
}
